/*
 * Блок-листы: скачивание пресетов (простые списки доменов) и сборка
 * единого blocked-names.txt для dnscrypt-proxy.
 */
const fs = require('fs');
const path = require('path');
const https = require('https');

const PRESETS = {
    ads: {
        label: 'Реклама и трекеры',
        url: 'https://raw.githubusercontent.com/sjhgvr/oisd/main/dbl_small.txt',
    },
    malware: {
        label: 'Фишинг и малварь',
        url: 'https://phishing.army/download/phishing_army_blocklist_extended.txt',
    },
};

function download(url, dest, redirects = 0) {
    return new Promise((resolve, reject) => {
        if (redirects > 5) return reject(new Error('слишком много редиректов'));
        https.get(url, { headers: { 'User-Agent': 'Invis' } }, (res) => {
            if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
                res.resume();
                return resolve(download(new URL(res.headers.location, url).href, dest, redirects + 1));
            }
            if (res.statusCode !== 200) { res.resume(); return reject(new Error(`HTTP ${res.statusCode}`)); }
            const out = fs.createWriteStream(dest);
            res.pipe(out);
            out.on('finish', () => out.close(resolve));
            out.on('error', reject);
        }).on('error', reject);
    });
}

/* Скачивает пресет, если файла ещё нет (кэш в configDir) */
async function ensure(configDir, name) {
    const preset = PRESETS[name];
    if (!preset) throw new Error(`неизвестный пресет: ${name}`);
    const dest = path.join(configDir, `preset-${name}.txt`);
    if (fs.existsSync(dest)) return dest;
    await download(preset.url, dest);
    return dest;
}

/* Собирает blocked-names.txt: canary браузерного DoH + активные пресеты.
 * Возвращает null, если блокировать нечего. */
function composeBlockedNames(configDir, cfg = {}) {
    const parts = [];
    if (cfg.blockBrowserDoh !== false) parts.push('# canary: отключаем встроенный DoH браузеров\nuse-application-dns.net');
    for (const key of Object.keys(PRESETS)) {
        if (!cfg.presets || !cfg.presets[key]) continue;
        try {
            const text = fs.readFileSync(path.join(configDir, `preset-${key}.txt`), 'utf8');
            parts.push(`# preset: ${key}\n${text}`);
        } catch (e) { /* пресет ещё не скачан — пропускаем */ }
    }
    if (!parts.length) return null;
    return '# generated by Invis\n' + parts.join('\n') + '\n';
}

module.exports = { PRESETS, download, ensure, composeBlockedNames };
