/*
 * Генераторы конфигов демонов. Пишутся в <base>/configs при каждом запуске
 * (истина — всегда в сгенерированном файле, prefs-редакторы появятся позже).
 * Модуль не зависит от Electron — используется и в рантайме, и в dev-проверках.
 */
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const blocklists = require('./blocklists');

const PORTS = {
    torSocks: 9050,
    torControl: 9051,
    torDns: 5400,
    dnscrypt: 9053,
    i2pHttp: 4444,
    i2pSocks: 4447,
    i2pConsole: 7070,
};

const fwd = (p) => p.split(path.sep).join('/');

/* Атомарная запись (SEC-9): демон при рестарте мог прочитать полусконфиг */
function writeAtomic(file, data) {
    const tmp = `${file}.tmp`;
    fs.writeFileSync(tmp, data, 'utf8');
    fs.renameSync(tmp, file);
}

/* Имена pluggable-транспортов → исполняемые файлы в bin/tor/.../pluggable_transports.
 * В комплекте только то, что реально лежит в bin (CLEAN-4): snowflake/webtunnel
 * не бандлились и генерировали битый torrc. */
const BRIDGE_PLUGINS = {
    obfs4: 'lyrebird.exe',
    conjure: 'conjure-client.exe',
};

/* Tor (mingw-сборка) не умеет в не-ASCII пути: «Couldn't create private data
 * directory». Для таких путей используем короткие 8.3 имена (FSO ShortPath). */
function shortPathSync(p) {
    try {
        const out = execFileSync('powershell', [
            '-NoProfile', '-NonInteractive', '-Command',
            `(New-Object -ComObject Scripting.FileSystemObject).GetFolder('${p.replace(/'/g, "''")}').ShortPath`,
        ], { encoding: 'utf8', windowsHide: true, timeout: 15000 });
        const short = out.trim();
        if (short && !/[^\x00-\x7F]/.test(short)) return short;
    } catch (e) { /* 8.3 отключены или ps не отработал — вернём как есть */ }
    return p;
}
const torPath = (p) => (/[^\x00-\x7F]/.test(p) ? shortPathSync(p) : p);

function torrc({ dataDir, bridges, pluginDir }) {
    const dd = fwd(torPath(dataDir));
    const lines = [
        '# generated by Invis — ручные правки будут перезаписаны',
        `SocksPort ${PORTS.torSocks}`,
        `ControlPort ${PORTS.torControl}`,
        'CookieAuthentication 1',
        'ClientOnly 1',
        'NoExec 1',
        `DataDirectory ${dd}`,
        `GeoIPFile ${dd}/geoip`,
        `GeoIPv6File ${dd}/geoip6`,
        'Log notice stdout',
    ];

    /* Мосты: строки вида "obfs4 1.2.3.4:443 cert=... iat-mode=0" (префикс Bridge опционален).
     * Транспорт определяется по первому слову первой строки. */
    if (bridges && bridges.use && Array.isArray(bridges.lines) && bridges.lines.length) {
        const clean = bridges.lines
            .map((l) => l.trim().replace(/^Bridge\s+/, ''))
            .filter((l) => l && !l.startsWith('#'));
        const transport = clean.length ? clean[0].split(/\s+/)[0] : '';
        /* Имя транспорта попадает в путь плагина — только строгие символы
         * (SEC-12): '..' и прочее отсекаем, блок мостов просто не пишем. */
        if (clean.length && /^[A-Za-z0-9_-]+$/.test(transport)) {
            const plugin = BRIDGE_PLUGINS[transport] || `${transport}-client.exe`;
            const pluginPath = fwd(torPath(path.join(pluginDir || '', plugin)));
            /* Плагина нет (не забандлен/опечатка) — мосты не пишем вовсе:
             * битый ClientTransportPlugin валит весь Tor (CLEAN-4) */
            if (fs.existsSync(path.join(pluginDir || '', plugin))) {
                lines.push('UseBridges 1');
                lines.push(`ClientTransportPlugin ${transport} exec "${pluginPath}"`);
                for (const l of clean) lines.push(`Bridge ${l}`);
            } else {
                lines.push(`# плагин транспорта «${transport}» (${plugin}) не найден — мосты отключены`);
            }
        }
    }
    /* Страны выхода: ограничиваем выходные узлы выбранными странами.
     * StrictNodes 1 — строго выбранные страны, иначе Tor молча уйдёт в другую */
    if (Array.isArray(bridges && bridges.exitCountries) && bridges.exitCountries.length) {
        const ccs = bridges.exitCountries
            .map((c) => String(c).toLowerCase().replace(/[^a-z]/g, ''))
            .filter((c) => c.length === 2);
        if (ccs.length) {
            lines.push(`ExitNodes ${ccs.map((c) => `{${c}}`).join(',')}`);
            lines.push('StrictNodes 1');
        }
    }
    lines.push('');
    return lines.join('\n');
}

/* Публичный minisign-ключ репозитория dnscrypt-resolvers (стандартный для dnscrypt-proxy). */
const RESOLVERS_MINISIGN_KEY = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3';

const tomlList = (arr) => '[' + arr.map((s) => `'${String(s).replace(/'/g, "''")}'`).join(', ') + ']';

/* cfg — раздел dnscrypt из настроек (см. store.js DEFAULTS.dnscrypt) */
function dnscryptToml(listenPort = PORTS.dnscrypt, cfg = {}) {
    /* При перехвате системного DNS слушаем оба loopback'а: Windows может
     * слать запросы и на 127.0.0.1, и на ::1 */
    const listen = cfg.lanAccess
        ? ['0.0.0.0:' + listenPort, '[::]:' + listenPort]
        : (listenPort === 53
            ? ['127.0.0.1:' + listenPort, '[::1]:' + listenPort]
            : ['127.0.0.1:' + listenPort]);
    const manual = !cfg.autoMode && Array.isArray(cfg.servers) && cfg.servers.length;
    const bootstrap = Array.isArray(cfg.bootstrap) && cfg.bootstrap.length
        ? cfg.bootstrap : ['9.9.9.9:53', '8.8.8.8:53'];

    return `# generated by Invis — ручные правки будут перезаписаны
listen_addresses = ${tomlList(listen)}
${manual ? `server_names = ${tomlList(cfg.servers)}\n` : ''}max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = ${cfg.dnscryptProto !== false}
doh_servers = ${cfg.dohProto !== false}
require_dnssec = ${Boolean(cfg.requireDnssec)}
require_nolog = ${cfg.requireNolog !== false}
require_nofilter = ${cfg.requireNofilter !== false}
force_tcp = ${Boolean(cfg.forceTcp)}
block_ipv6 = ${Boolean(cfg.blockIpv6)}
timeout = 5000
keepalive = 30
cert_refresh_delay = 240
bootstrap_resolvers = ${tomlList(bootstrap)}
ignore_system_dns = true
netprobe_timeout = -1
log_level = 0
log_file = ''
use_syslog = false
cache = ${cfg.cache !== false}
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
blocked_query_response = 'refused'
${cfg.queryLog ? `
[query_log]
  file = 'query.log'
  format = 'tsv'
` : ''}${cfg.hasBlockedNames ? `
[blocked_names]
  blocked_names_file = 'blocked-names.txt'
` : ''}[sources]

  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = '${RESOLVERS_MINISIGN_KEY}'
  refresh_delay = 72

  [sources.'relays']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md']
  cache_file = 'relays.md'
  minisign_key = '${RESOLVERS_MINISIGN_KEY}'
  refresh_delay = 72
`;
}

function i2pdConf() {
    return `# generated by Invis — ручные правки будут перезаписаны
# datadir/certsdir задаются CLI-аргументами (--datadir/--certsdir):
# ключ datadir внутри ini i2pd игнорирует
log=stdout
loglevel=warn

[http]
enabled=true
address=127.0.0.1
port=${PORTS.i2pConsole}

[httpproxy]
enabled=true
address=127.0.0.1
port=${PORTS.i2pHttp}

[socksproxy]
enabled=true
address=127.0.0.1
port=${PORTS.i2pSocks}

[addressbook]
# b32-подпись hosts.txt (stats.i2p) — резолвинг имён вида stats.i2p
subscriptions = http://udhdrtrcetjm5sxzskjyr5zdbes6uzapvyqmza5jmcljvxyzarq.b32.i2p/hosts.txt
`;
}

/*
 * Пишет все конфиги и готовит каталоги данных.
 * geoip копируется в каталог данных Tor (в torrc пути идут внутрь DataDirectory).
 * dnscryptListen: 9053 (обычный режим) или 53 (перехват системного DNS).
 * dnscryptCfg — раздел dnscrypt настроек; torCfg — раздел tor (мосты).
 */
function buildAll({ configDir, torDataDir, i2pDataDir, geoipDir, i2pdContribDir,
                    dnscryptListen = PORTS.dnscrypt, dnscryptCfg = {}, torCfg = {}, torPluginDir }) {
    for (const dir of [configDir, torDataDir, i2pDataDir]) fs.mkdirSync(dir, { recursive: true });
    /* i2pd нужны reseed-сертификаты в <datadir>/certificates */
    const i2pCerts = path.join(i2pDataDir, 'certificates');
    if (i2pdContribDir && !fs.existsSync(i2pCerts)) {
        fs.cpSync(path.join(i2pdContribDir, 'certificates'), i2pCerts, { recursive: true });
    }
    /* geoip — рядом с данными Tor, один раз */
    for (const f of ['geoip', 'geoip6']) {
        const dst = path.join(torDataDir, f);
        if (geoipDir && !fs.existsSync(dst)) fs.copyFileSync(path.join(geoipDir, f), dst);
    }
    writeAtomic(path.join(configDir, 'torrc'), torrc({
        dataDir: torDataDir,
        bridges: {
            use: Boolean(torCfg.useBridges),
            lines: String(torCfg.bridgesText || '').split(/\r?\n/),
            exitCountries: torCfg.exitCountries,
        },
        pluginDir: torPluginDir,
    }));
    /* composeBlockedNames читает мегабайтные пресеты — один раз, не дважды */
    const blocked = blocklists.composeBlockedNames(configDir, dnscryptCfg);
    writeAtomic(path.join(configDir, 'dnscrypt-proxy.toml'), dnscryptToml(dnscryptListen, {
        ...dnscryptCfg,
        hasBlockedNames: Boolean(blocked),
    }));
    if (blocked) writeAtomic(path.join(configDir, 'blocked-names.txt'), blocked);
    else try { fs.unlinkSync(path.join(configDir, 'blocked-names.txt')); } catch (e) { /* не было */ }
    writeAtomic(path.join(configDir, 'i2pd.conf'), i2pdConf());
    return {
        torrc: path.join(configDir, 'torrc'),
        dnscryptToml: path.join(configDir, 'dnscrypt-proxy.toml'),
        i2pdConf: path.join(configDir, 'i2pd.conf'),
    };
}

module.exports = { PORTS, buildAll, shortPathSync };
