/*
 * Блок-листы: скачивание пресетов (простые списки доменов) и сборка
 * единого blocked-names.txt для dnscrypt-proxy.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as https from 'https';

export interface Preset {
    label: string;
    url: string;
}

export const PRESETS: Record<string, Preset> = {
    ads: {
        label: 'Реклама и трекеры',
        url: 'https://raw.githubusercontent.com/sjhgvr/oisd/main/dbl_small.txt',
    },
    malware: {
        label: 'Фишинг и малварь',
        url: 'https://phishing.army/download/phishing_army_blocklist_extended.txt',
    },
};

const DOWNLOAD_TIMEOUT_MS = 60000;
/* Списки доменов меняются — раз скачанный «навсегда» устаревал (SIM-2).
 * Совпадает с TTL кэша Onionoo. */
const REFRESH_MS = 24 * 60 * 60 * 1000;

export function download(url: string, dest: string, redirects = 0): Promise<string> {
    return new Promise((resolve, reject) => {
        if (redirects > 5) { reject(new Error('слишком много редиректов')); return; }
        const part = `${dest}.part`;
        let overall: NodeJS.Timeout | null = null;
        const fail = (err: Error) => {
            if (overall) clearTimeout(overall);
            /* Обрыв не должен оставлять «навсегда валидный» обрезанный файл */
            try { fs.unlinkSync(part); } catch (e) { /* ещё не создан */ }
            reject(err);
        };
        const done = () => {
            if (overall) clearTimeout(overall);
            try { fs.renameSync(part, dest); resolve(dest); }
            catch (e) { reject(e as Error); }
        };
        /* Общий таймаут: зависший сервер раньше вешал включение пресета навсегда */
        const req = https.get(url, { headers: { 'User-Agent': 'Invis' } }, (res) => {
            const code = res.statusCode ?? 0;
            if (code >= 300 && code < 400 && res.headers.location) {
                res.resume();
                if (overall) clearTimeout(overall);
                resolve(download(new URL(res.headers.location, url).href, dest, redirects + 1));
                return;
            }
            if (code !== 200) { res.resume(); reject(new Error(`HTTP ${code}`)); return; }
            const out = fs.createWriteStream(part);
            res.pipe(out);
            res.on('error', fail);
            out.on('error', fail);
            out.on('finish', done);
        });
        req.on('error', fail);
        overall = setTimeout(() => req.destroy(new Error('таймаут загрузки блок-листа')), DOWNLOAD_TIMEOUT_MS);
    });
}

/* Возвращает пресет, докачивая при отсутствии; если файл старше суток —
 * перекачивает. При ошибке обновления старый файл остаётся: устаревший
 * список лучше отсутствующего.
 * Возвращает { dest, refreshed } (refreshed=true — реально скачан сейчас). */
export async function ensure(configDir: string, name: string): Promise<{ dest: string; refreshed: boolean }> {
    const preset = PRESETS[name];
    if (!preset) throw new Error(`неизвестный пресет: ${name}`);
    const dest = path.join(configDir, `preset-${name}.txt`);
    if (fs.existsSync(dest)) {
        const fresh = (Date.now() - fs.statSync(dest).mtimeMs) < REFRESH_MS;
        if (fresh) return { dest, refreshed: false };
        try {
            await download(preset.url, dest);
            return { dest, refreshed: true };
        } catch (e) {
            return { dest, refreshed: false };
        }
    }
    try { fs.unlinkSync(`${dest}.part`); } catch (e) { /* не было */ }
    await download(preset.url, dest);
    return { dest, refreshed: true };
}

/* Собирает blocked-names.txt: canary браузерного DoH + активные пресеты.
 * Возвращает null, если блокировать нечего. */
export function composeBlockedNames(
    configDir: string,
    cfg: { blockBrowserDoh?: boolean; presets?: object } = {},
): string | null {
    const parts = [];
    if (cfg.blockBrowserDoh !== false) parts.push('# canary: отключаем встроенный DoH браузеров\nuse-application-dns.net');
    const presets = (cfg.presets || {}) as Record<string, boolean>;
    for (const key of Object.keys(PRESETS)) {
        if (!presets[key]) continue;
        try {
            const text = fs.readFileSync(path.join(configDir, `preset-${key}.txt`), 'utf8');
            parts.push(`# preset: ${key}\n${text}`);
        } catch (e) { /* пресет ещё не скачан — пропускаем */ }
    }
    if (!parts.length) return null;
    return '# generated by Invis\n' + parts.join('\n') + '\n';
}
