/*
 * Блок-листы: скачивание пресетов (простые списки доменов) и сборка
 * единого blocked-names.txt для dnscrypt-proxy.
 */
const fs = require('fs');
const path = require('path');
const https = require('https');

const PRESETS = {
    ads: {
        label: 'Реклама и трекеры',
        url: 'https://raw.githubusercontent.com/sjhgvr/oisd/main/dbl_small.txt',
    },
    malware: {
        label: 'Фишинг и малварь',
        url: 'https://phishing.army/download/phishing_army_blocklist_extended.txt',
    },
};

const DOWNLOAD_TIMEOUT_MS = 60000;
/* Списки доменов меняются — раз скачанный «навсегда» устаревал (SIM-2).
 * Совпадает с TTL кэша Onionoo. */
const REFRESH_MS = 24 * 60 * 60 * 1000;

function download(url, dest, redirects = 0) {
    return new Promise((resolve, reject) => {
        if (redirects > 5) return reject(new Error('слишком много редиректов'));
        const part = `${dest}.part`;
        let overall = null;
        const fail = (err) => {
            if (overall) clearTimeout(overall);
            /* Обрыв не должен оставлять «навсегда валидный» обрезанный файл */
            try { fs.unlinkSync(part); } catch (e) { /* ещё не создан */ }
            reject(err);
        };
        const done = () => {
            if (overall) clearTimeout(overall);
            try { fs.renameSync(part, dest); resolve(dest); }
            catch (e) { reject(e); }
        };
        /* Общий таймаут: зависший сервер раньше вешал включение пресета навсегда */
        const req = https.get(url, { headers: { 'User-Agent': 'Invis' } }, (res) => {
            if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
                res.resume();
                if (overall) clearTimeout(overall);
                return resolve(download(new URL(res.headers.location, url).href, dest, redirects + 1));
            }
            if (res.statusCode !== 200) { res.resume(); return reject(new Error(`HTTP ${res.statusCode}`)); }
            const out = fs.createWriteStream(part);
            res.pipe(out);
            res.on('error', fail);
            out.on('error', fail);
            out.on('finish', done);
        });
        req.on('error', fail);
        overall = setTimeout(() => req.destroy(new Error('таймаут загрузки блок-листа')), DOWNLOAD_TIMEOUT_MS);
    });
}

/* Возвращает пресет, докачивая при отсутствии; если файл старше суток —
 * перекачивает в фоне того же вызова. При ошибке обновления старый файл
 * остаётся: устаревший список лучше отсутствующего.
 * Возвращает { dest, refreshed } (refreshed=true — реально скачан сейчас). */
async function ensure(configDir, name) {
    const preset = PRESETS[name];
    if (!preset) throw new Error(`неизвестный пресет: ${name}`);
    const dest = path.join(configDir, `preset-${name}.txt`);
    if (fs.existsSync(dest)) {
        const fresh = (Date.now() - fs.statSync(dest).mtimeMs) < REFRESH_MS;
        if (fresh) return { dest, refreshed: false };
        try {
            await download(preset.url, dest);
            return { dest, refreshed: true };
        } catch (e) {
            return { dest, refreshed: false };
        }
    }
    try { fs.unlinkSync(`${dest}.part`); } catch (e) { /* не было */ }
    await download(preset.url, dest);
    return { dest, refreshed: true };
}

/* Собирает blocked-names.txt: canary браузерного DoH + активные пресеты.
 * Возвращает null, если блокировать нечего. */
function composeBlockedNames(configDir, cfg = {}) {
    const parts = [];
    if (cfg.blockBrowserDoh !== false) parts.push('# canary: отключаем встроенный DoH браузеров\nuse-application-dns.net');
    for (const key of Object.keys(PRESETS)) {
        if (!cfg.presets || !cfg.presets[key]) continue;
        try {
            const text = fs.readFileSync(path.join(configDir, `preset-${key}.txt`), 'utf8');
            parts.push(`# preset: ${key}\n${text}`);
        } catch (e) { /* пресет ещё не скачан — пропускаем */ }
    }
    if (!parts.length) return null;
    return '# generated by Invis\n' + parts.join('\n') + '\n';
}

module.exports = { PRESETS, download, ensure, composeBlockedNames };
